steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/bangalore-sandbox/orders', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/bangalore-sandbox/orders']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'orders', '--image', 'gcr.io/bangalore-sandbox/orders', '--region', 'asia-south1']
images:
- asia-south1-docker.pkg.dev/bangalore-sandbox/orders